version: '3.8'

services:
  app:
    build: .
    container_name: invoice-system
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./invoices.db:/app/invoices.db
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - DEBUG=False
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - USE_SUPABASE_STORAGE=${USE_SUPABASE_STORAGE:-false}
      - DATA_BACKEND=${DATA_BACKEND:-sqlite}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: invoice-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - with-nginx

volumes:
  uploads:
  database:
